"""Model service for AI interactions."""
from abc import ABC, abstractmethod
import random
import re


class ModelAdapter(ABC):
    """Base class for model adapters."""
    
    @abstractmethod
    def generate(self, prompt, user=None):
        """Generate a response from the model."""
        pass
    
    @abstractmethod
    def get_name(self):
        """Get model name."""
        pass


class LlamaCppAdapter(ModelAdapter):
    """Adapter for llama.cpp models."""
    
    def __init__(self, model_path=None):
        self.model_path = model_path
        # In production, initialize llama.cpp here
        # For now, this is a placeholder/mock
    
    def generate(self, prompt, user=None):
        """Generate response using llama.cpp - optimized for document processing."""
        # Mock implementation - replace with actual llama.cpp integration
        file_responses = [
            f"[Llama.cpp - Document Processing]\n\nAnalyzing document content: {prompt[:80]}...\n\nKey information extracted:\n- Document structure analysis\n- Content summarization\n- Key points identification\n\nNote: This is a mock response. Production version will process actual documents and large files.",
            f"[Llama.cpp File Processor]\n\nProcessing request: {prompt[:100]}...\n\nFor large files and documents, I can:\n- Extract and parse content\n- Summarize lengthy documents\n- Analyze structured data (CSV, JSON, etc.)\n\nPlaceholder response for development.",
            f"[Llama.cpp - Fast Document AI]\n\nDocument task: {prompt[:80]}...\n\nCapabilities:\n✓ PDF text extraction\n✓ Large file processing\n✓ Document summarization\n✓ Data analysis\n\nMock implementation. Real model will process actual files efficiently."
        ]
        return random.choice(file_responses)
    
    def get_name(self):
        return "llama.cpp"


class GPT4AllAdapter(ModelAdapter):
    """Adapter for GPT4All models."""
    
    def __init__(self, model_path=None):
        self.model_path = model_path
        # In production, initialize GPT4All here
        # For now, this is a placeholder/mock
    
    def generate(self, prompt, user=None):
        """Generate response using GPT4All."""
        # Mock implementation - replace with actual GPT4All integration
        responses = [
            f"Based on your query: {prompt[:50]}...\n\nHere's what I can tell you:",
            f"Let me analyze your question about {prompt[:30]}...\n\nThe key points are:",
            f"Interesting question! Regarding {prompt[:40]}...\n\nConsider the following:"
        ]
        return random.choice(responses) + f"\n\n[Response generated by GPT4All model - mock implementation]"
    
    def get_name(self):
        return "gpt4all"


class DeepSeekAdapter(ModelAdapter):
    """Adapter for DeepSeek models."""
    
    def __init__(self, model_path=None):
        self.model_path = model_path
        # In production, initialize DeepSeek here
    
    def generate(self, prompt, user=None):
        """Generate response using DeepSeek - specialized for coding."""
        # Mock implementation - replace with actual DeepSeek integration
        coding_responses = [
            f"[DeepSeek Coder]\n\nAnalyzing your code request: {prompt[:80]}...\n\n```python\n# Here's a solution approach:\ndef example_function():\n    # Implementation details\n    pass\n```\n\nExplanation: This is a mock response. In production, DeepSeek will provide actual code analysis and solutions.",
            f"[DeepSeek Coder]\n\nI'll help you with this coding task.\n\nKey considerations:\n1. Code structure and best practices\n2. Error handling\n3. Performance optimization\n\n```\n// Sample implementation\n// {prompt[:60]}...\n```\n\nNote: This is a placeholder. Real DeepSeek model will provide detailed code assistance.",
            f"[DeepSeek Coder - Code Analysis]\n\nTask: {prompt[:100]}...\n\nRecommended approach:\n- Use appropriate design patterns\n- Follow language-specific conventions\n- Include proper error handling\n\nMock implementation provided. Production version will use actual DeepSeek Coder model."
        ]
        return random.choice(coding_responses)
    
    def get_name(self):
        return "deepseek"


class VicunaAdapter(ModelAdapter):
    """Adapter for Vicuna models."""
    
    def __init__(self, model_path=None):
        self.model_path = model_path
        # In production, initialize Vicuna here
    
    def generate(self, prompt, user=None):
        """Generate response using Vicuna - specialized for multimodal content."""
        # Mock implementation - replace with actual Vicuna integration
        multimodal_responses = [
            f"[Vicuna - Multimodal Analysis]\n\nAnalyzing your content request: {prompt[:80]}...\n\nFor image/video content:\n- I can process visual information\n- Extract key features and descriptions\n- Provide detailed analysis\n\nNote: This is a mock response. Production version will process actual image/video data.",
            f"[Vicuna Vision Model]\n\nContent type: Image/Video processing\nQuery: {prompt[:100]}...\n\nIn production, I will:\n- Analyze visual content\n- Identify objects and scenes\n- Provide comprehensive descriptions\n\nPlaceholder response for development.",
            f"[Vicuna - Visual AI]\n\nTask: {prompt[:80]}...\n\nMultimodal capabilities:\n✓ Image recognition\n✓ Video analysis\n✓ Scene understanding\n✓ Content description\n\nMock implementation. Real model will process actual media files."
        ]
        return random.choice(multimodal_responses)
    
    def get_name(self):
        return "vicuna"


# Model registry
MODELS = {
    'llama': LlamaCppAdapter(),
    'gpt4all': GPT4AllAdapter(),
    'deepseek': DeepSeekAdapter(),
    'vicuna': VicunaAdapter()
}


def detect_content_type(prompt):
    """Detect content type from prompt to select appropriate model.
    
    Returns:
        str: Content type - 'code', 'file', 'pdf', 'image', 'video', 'general'
    """
    prompt_lower = prompt.lower()
    
    # Coding keywords
    coding_keywords = [
        'code', 'function', 'class', 'programming', 'debug', 'error',
        'python', 'javascript', 'java', 'c++', 'rust', 'go', 'php',
        'html', 'css', 'sql', 'algorithm', 'api', 'backend', 'frontend',
        'bug', 'syntax', 'compile', 'execute', 'script', 'package',
        'import', 'export', 'variable', 'loop', 'conditional', 'refactor',
        'optimize code', 'write code', 'fix code', 'review code',
        'implementation', 'coding', 'developer', 'program'
    ]
    
    # File processing keywords
    file_keywords = ['file', 'document', 'upload', 'large file', 'csv', 'json', 'xml', 'yaml']
    
    # PDF keywords
    pdf_keywords = ['pdf', 'document analysis', 'extract text', 'read pdf']
    
    # Image/photo keywords
    image_keywords = ['image', 'photo', 'picture', 'jpeg', 'png', 'analyze image', 'vision']
    
    # Video keywords
    video_keywords = ['video', 'mp4', 'avi', 'analyze video', 'video processing']
    
    # Check for coding content
    if any(keyword in prompt_lower for keyword in coding_keywords):
        return 'code'
    
    # Check for PDF content
    if any(keyword in prompt_lower for keyword in pdf_keywords):
        return 'pdf'
    
    # Check for image content
    if any(keyword in prompt_lower for keyword in image_keywords):
        return 'image'
    
    # Check for video content
    if any(keyword in prompt_lower for keyword in video_keywords):
        return 'video'
    
    # Check for file content
    if any(keyword in prompt_lower for keyword in file_keywords):
        return 'file'
    
    # Check for code blocks or patterns
    if '```' in prompt or re.search(r'def |class |function |import |const |var |let ', prompt):
        return 'code'
    
    return 'general'


def select_model_for_content(prompt, requested_model=None):
    """Select appropriate model based on content type.
    
    Args:
        prompt: User prompt/message
        requested_model: User-requested model (optional)
    
    Returns:
        str: Model name to use
    """
    # If user specifically requested a model, use it
    if requested_model and requested_model in MODELS:
        return requested_model
    
    content_type = detect_content_type(prompt)
    
    # Route to appropriate model based on content type
    if content_type == 'code':
        # Use DeepSeek for coding tasks
        return 'deepseek'
    elif content_type in ['pdf', 'file']:
        # Use Llama for file/document processing
        return 'llama'
    elif content_type in ['image', 'video']:
        # Use Vicuna for multimodal content
        return 'vicuna'
    else:
        # Use GPT4All for general chat
        return 'gpt4all'


def get_model_response(prompt, model_name='auto', user=None):
    """Get response from specified model.
    
    Args:
        prompt: User prompt/message
        model_name: Model to use ('auto' for automatic selection)
        user: User object
    
    Returns:
        str: AI response
    """
    # Auto-select model based on content if requested
    if model_name == 'auto':
        model_name = select_model_for_content(prompt)
    elif model_name not in MODELS:
        model_name = 'gpt4all'
    
    model = MODELS[model_name]
    
    # Add content type info to response for debugging in mock mode
    content_type = detect_content_type(prompt)
    response = model.generate(prompt, user)
    
    # Add routing info in development
    if content_type != 'general':
        response += f"\n\n[Content type detected: {content_type}, Model selected: {model_name}]"
    
    return response


def get_available_models():
    """Get list of available models."""
    return [
        {
            'id': 'auto',
            'name': 'Auto-Select',
            'description': 'Automatically selects the best model for your task',
            'recommended': True
        },
        {
            'id': 'deepseek',
            'name': 'DeepSeek Coder',
            'description': 'Specialized for coding, debugging, and programming tasks',
            'use_case': 'Coding & Development'
        },
        {
            'id': 'gpt4all',
            'name': 'GPT4All',
            'description': 'General purpose conversational AI for everyday tasks',
            'use_case': 'General Chat'
        },
        {
            'id': 'llama',
            'name': 'Llama.cpp',
            'description': 'Optimized for document processing and large files',
            'use_case': 'Files & Documents'
        },
        {
            'id': 'vicuna',
            'name': 'Vicuna',
            'description': 'Multimodal model for images, videos, and rich content',
            'use_case': 'Images & Videos'
        }
    ]
